Ingredient.create(name: "151 proof rum")
Ingredient.create(name: "7-Up")
Ingredient.create(name: "Absinthe")
Ingredient.create(name: "Absolut Citron")
Ingredient.create(name: "Absolut Kurant")
Ingredient.create(name: "Absolut Vodka")
Ingredient.create(name: "Advocaat")
Ingredient.create(name: "Ale")
Ingredient.create(name: "Amaretto")
Ingredient.create(name: "Añejo rum")
Ingredient.create(name: "Angelica root")
Ingredient.create(name: "Aplejack")
Ingredient.create(name: "Apple brandy")
Ingredient.create(name: "Apple cider")
Ingredient.create(name: "Apple juice")
Ingredient.create(name: "Apricot brandy")
Ingredient.create(name: "Bacardi Limon")
Ingredient.create(name: "Baileys irish cream")
Ingredient.create(name: "Banana liqueur")
Ingredient.create(name: "Beer")
Ingredient.create(name: "Berries")
Ingredient.create(name: "Bitters")
Ingredient.create(name: "Black Sambuca")
Ingredient.create(name: "Blackberry brandy")
Ingredient.create(name: "Blended Scotch")
Ingredient.create(name: "Blended whiskey")
Ingredient.create(name: "Blue Curacao")
Ingredient.create(name: "Bourbon")
Ingredient.create(name: "Brandy")
Ingredient.create(name: "Cachaca")
Ingredient.create(name: "Campari")
Ingredient.create(name: "Cantaloupe")
Ingredient.create(name: "Carbonated water")
Ingredient.create(name: "Chambord raspberry liqueur")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Cherry")
Ingredient.create(name: "Cherry brandy")
Ingredient.create(name: "Cherry Heering")
Ingredient.create(name: "Chocolate")
Ingredient.create(name: "Chocolate ice-cream")
Ingredient.create(name: "Chocolate liqueur")
Ingredient.create(name: "Chocolate syrup")
Ingredient.create(name: "Cider")
Ingredient.create(name: "Coca-Cola")
Ingredient.create(name: "Cocoa powder")
Ingredient.create(name: "Coconut rum")
Ingredient.create(name: "Coffee")
Ingredient.create(name: "Coffee brandy")
Ingredient.create(name: "Coffee liqueur")
Ingredient.create(name: "Cognac")
Ingredient.create(name: "Cointreau")
Ingredient.create(name: "Corona")
Ingredient.create(name: "Cranberries")
Ingredient.create(name: "Cranberry juice")
Ingredient.create(name: "Cranberry vodka")
Ingredient.create(name: "Creme de Cacao")
Ingredient.create(name: "Creme de Cassis")
Ingredient.create(name: "Crown Royal")
Ingredient.create(name: "Dark rum")
Ingredient.create(name: "Demerara Sugar")
Ingredient.create(name: "Dry Vermouth")
Ingredient.create(name: "Dubonnet Rouge")
Ingredient.create(name: "Egg")
Ingredient.create(name: "Egg yolk")
Ingredient.create(name: "Espresso")
Ingredient.create(name: "Everclear")
Ingredient.create(name: "Firewater")
Ingredient.create(name: "Frangelico")
Ingredient.create(name: "Fruit punch")
Ingredient.create(name: "Galliano")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Ginger")
Ingredient.create(name: "Godiva liqueur")
Ingredient.create(name: "Goldschlager")
Ingredient.create(name: "Grapefruit juice")
Ingredient.create(name: "Grenadine")
Ingredient.create(name: "Grand Marnier")
Ingredient.create(name: "Grape juice")
Ingredient.create(name: "Grape Soda")
Ingredient.create(name: "Grapes")
Ingredient.create(name: "Green Chartreuse")
Ingredient.create(name: "Green Creme de Menthe")
Ingredient.create(name: "Guinness stout")
Ingredient.create(name: "Heavy cream")
Ingredient.create(name: "Hot Chocolate")
Ingredient.create(name: "Hot Damn")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Irish cream")
Ingredient.create(name: "Irish whiskey")
Ingredient.create(name: "Jack Daniels")
Ingredient.create(name: "Jägermeister")
Ingredient.create(name: "Jim Beam")
Ingredient.create(name: "Johnnie Walker")
Ingredient.create(name: "Kahlua")
Ingredient.create(name: "Kiwi")
Ingredient.create(name: "Kiwi liqueur")
Ingredient.create(name: "Kool-Aid")
Ingredient.create(name: "Lager")
Ingredient.create(name: "Lemon")
Ingredient.create(name: "Lemonade")
Ingredient.create(name: "Lemon juice")
Ingredient.create(name: "Lemon peel")
Ingredient.create(name: "Lemon vodka")
Ingredient.create(name: "Light rum")
Ingredient.create(name: "Lime")
Ingredient.create(name: "Lime juice")
Ingredient.create(name: "Malibu rum")
Ingredient.create(name: "Mango")
Ingredient.create(name: "Maui")
Ingredient.create(name: "Mezcal")
Ingredient.create(name: "Midori melon liqueur")
Ingredient.create(name: "Milk")
Ingredient.create(name: "Mint")
Ingredient.create(name: "Orange")
Ingredient.create(name: "Orange bitters")
Ingredient.create(name: "Orange juice")
Ingredient.create(name: "Orange wedge")
Ingredient.create(name: "Ouzo")
Ingredient.create(name: "Peach nectar")
Ingredient.create(name: "Peach Vodka")
Ingredient.create(name: "Peachtree schnapps")
Ingredient.create(name: "Peppermint schnapps")
Ingredient.create(name: "Pineapple juice")
Ingredient.create(name: "Pisco")
Ingredient.create(name: "Port")
Ingredient.create(name: "Prosecco")
Ingredient.create(name: "Raspberry vodka")
Ingredient.create(name: "Red wine")
Ingredient.create(name: "Ricard")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Rye whiskey")
Ingredient.create(name: "Sambuca")
Ingredient.create(name: "Scotch")
Ingredient.create(name: "Sherry")
Ingredient.create(name: "Sloe gin")
Ingredient.create(name: "Soda water")
Ingredient.create(name: "Sour mix")
Ingredient.create(name: "Southern Comfort")
Ingredient.create(name: "Spiced rum")
Ingredient.create(name: "Sprite")
Ingredient.create(name: "Strawberries")
Ingredient.create(name: "Strawberry schnapps")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Sugar syrup")
Ingredient.create(name: "Sweet Vermouth")
Ingredient.create(name: "Tea")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Tomato juice")
Ingredient.create(name: "Triple sec")
Ingredient.create(name: "Vanilla ice-cream")
Ingredient.create(name: "Vanilla vodka")
Ingredient.create(name: "Vermouth")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Water")
Ingredient.create(name: "Whiskey")
Ingredient.create(name: "White Creme de Menthe")
Ingredient.create(name: "White Rum")
Ingredient.create(name: "Wild Turkey")
Ingredient.create(name: "Yoghurt")
Ingredient.create(name: "Yukon Jack")
Ingredient.create(name: "Zima")

